---
- name: '[dependencies] Install ohmyzsh dependencies for non-Darwin systems: zsh, git'
  package:
    name: [ 'zsh', 'git', 'bc' ]
    state: present
  become: yes  # disable this for MacOS
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when: "'Darwin' not in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies

- name: '[dependencies] Make sure locales package is installed on Debian'
  apt: name=locales state=present
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when: "'Debian' in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies

# MacOS:
- name: '[dependencies] Install powerlevel9k dependencies: bc'
  homebrew: name=bc state=present
  become: no  # always the case with homebrew
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when:
  - ohmyzsh_powerlevel9k
  - "'Darwin' in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies

- name: '[dependencies] Install fzf'
  homebrew: name=fzf state=present
  become: no  # always the case with homebrew
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when:
  - "'Darwin' in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies

- name: '[dependencies] Install fzf useful key bindings and fuzzy completion'
  command: /usr/local/opt/fzf/install --key-bindings --completion --update-rc
  changed_when: false
  when:
  - "'Darwin' in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies

- name: '[dependencies] Install zsh on MacOS'
  homebrew: name=zsh state=present
  become: no
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when: "'Darwin' in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies
...