---
- name: '[install] Clone oh-my-zsh repo'
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ ohmyzsh_install_dir }}"
    version: master
    update: yes
  become: yes
  tags: ohmyzsh

- name: '[install] Clone Powerlevel9k theme to custom directory'
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ ohmyzsh_install_dir }}/custom/powerlevel9k"
    version: master
    update: yes
  become: yes
  when: ohmyzsh_powerlevel9k is defined and true
  tags: ohmyzsh

- name: '[install] Clone powerlevel10k theme to custom directory'
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ohmyzsh_install_dir }}/custom/powerlevel10k"
    version: master
    update: yes
  become: yes
  when: ohmyzsh_powerlevel10k is defined and true
  tags: ohmyzsh

- name: '[install] Make it fish-like: Clone zsh-autosuggestions plugin'
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ohmyzsh_install_dir }}/custom/plugins/zsh-autosuggestions"
    version: master
    update: yes
  become: yes
  tags: ohmyzsh

- name: '[install] Make it fish-like: Clone zsh-history-substring-search plugin'
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search
    dest: "{{ ohmyzsh_install_dir }}/custom/plugins/zsh-history-substring-search"
    version: master
    update: yes
  become: yes
  tags: ohmyzsh

- name: '[install] Make it fish-like: Clone zsh-syntax-highlighting plugin'
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ohmyzsh_install_dir }}/custom/plugins/zsh-syntax-highlighting"
    version: master
    update: yes
  become: yes
  tags: ohmyzsh

- name: '[install] Setup zprofile for zsh'
  template:
    src: zprofile.j2
    dest: "{{ ohmyzsh_zprofile_dir }}/zprofile"
    mode: 0644
    owner: root
    group: root
  become: yes
  when: "'Darwin' not in ansible_os_family"
  tags: ohmyzsh

# For Debian and maybe other distros:
- name: '[install] Set up en_US.UTF-8 locale'
  locale_gen:
    name: en_US.UTF-8
    state: present
  when:
  - "'Darwin' not in ansible_os_family"
  - "'RedHat' not in ansible_os_family"
  become: yes
  tags: ohmyzsh
...